{% from "opg-docker-monitoring/map.jinja" import monitoring with context %}

elasticcurator:
  image: registry.service.dsd.io/opguk/elasticsearch:latest
  external_links:
    - monitoringserver_elasticsearch_1:elasticsearch

